package au.edu.uts.aip.domain.entity;

/*the needed libraries imported here*/
import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * A Data model class related to the BOOK table in the database.
 * Book entity describes the a book object
 * It has properties id, name, tile and price
 * All the attributes of this model class are private attributes 
 * and all of them have relative get and set functions in order to access the attributes
 * 
 * @author 
 */
@NamedQueries({
    @NamedQuery(name="Book.getLatest", query="SELECT b FROM Book b ORDER BY b.publishYear DESC")
})
@Entity
public class Book implements Serializable {

    
    /**
     * The definition of the attributes of Book entity
     * the id of the book is generated automatically by the database;
     * the name is the author name;
     * title describes the title of the book;
     * the price describes the book price;
     * 
    */
    private Long id;
    private String name;
    private String title;
    private List<BookSeller> sellers;
    private String isbn;
    private int publishYear;
    private String publisher;
    private String imgPath;
    
    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    
    
    /**
     * The id of the book entity in Book table
     * Not null value
     * The type of the value is long;
     * it will be generated by database, it relates to the primary key of the Book Table
     * 
     * @return a long value
     */
    @Id
    @GeneratedValue
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    
    /**
     * The author name of the book entity in Book table
     * Not null value
     * The type : String 
     * @return a String value
     */
    @Column(nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    
     /**
     * The title of the book entity in Book table
     * Not null value
     * The type : String 
     * @return a String value
     */
    @Column(nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    
    @OneToMany(mappedBy = "book")
    public List<BookSeller> getSellers() {
        return sellers;
    }

    public void setSellers(List<BookSeller> sellers) {
        this.sellers = sellers;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public int getPublishYear() {
        return publishYear;
    }

    public void setPublishYear(int publishYear) {
        this.publishYear = publishYear;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
}
