package au.edu.uts.aip.domain.entity;

/*the needed libraries imported here*/
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


/**
 * A Data model class related to the BOOK table in the database.
 * Book entity describes the a book object
 * It has properties id, name, tile and price
 * All the attributes of this model class are private attributes 
 * and all of them have relative get and set functions in order to access the attributes
 * 
 * @author 
 */
@Entity
public class Book implements Serializable {

    
    /**
     * The definition of the attributes of Book entity
     * the id of the book is generated automatically by the database;
     * the name is the author name;
     * title describes the title of the book;
     * the price describes the book price;
     * 
    */
    private Long id;
    private String name;
    private String title;
    private double price;

    
    
    /**
     * The id of the book entity in Book table
     * Not null value
     * The type of the value is long;
     * it will be generated by database, it relates to the primary key of the Book Table
     * 
     * @return a long value
     */
    @Id
    @GeneratedValue
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    
    /**
     * The author name of the book entity in Book table
     * Not null value
     * The type : String 
     * @return a String value
     */
    @Column(nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    
     /**
     * The title of the book entity in Book table
     * Not null value
     * The type : String 
     * @return a String value
     */
    @Column(nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    
     /**
     * The price of the book entity in Book table
     * Not null value
     * The type : double
     * @return a double value
     */
    @Column(nullable = false)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    
}
