package au.edu.uts.aip.domain.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;



/**
 * A Data model class to access data in the Bookstore_Role table. Role describes the roles of the website user
 * It has properties Id and roleName. 
 * All the attributes of this model class are private attributes and all of them have relative get and set functions in
 * order to access the attributes
 *
 * @author
 */
@Entity
@Table(name = "Bookstore_Role")
@NamedQueries({
    @NamedQuery(name = "Role.find", query = "SELECT r from Role r where r.roleName=:name")
})
public class Role implements Serializable {
    /**
     * The definition of the attributes of Role class 
     * all Private attributes
     */
    private int Id;
    private String roleName;

    public enum RoleType {
        ADMIN("ADMIN"), USER("USER"), INACTIVATED("INACTIVATED"),
        VERIFYING("VERIFYING USER"), VERIFIED("VERIFIED USER"), BANNED("BANNED");

        private final String type;

        private RoleType(String type) {
            this.type = type;
        }

        @Override
        public String toString() {
            return type;
        }
    }

    
     /**
     * The id of the Role in Bookstore_Role table 
     * Automatically generated by the database 
     * Not null value
     * Get and Set functions to access the attribute
     * @return a int
     */
    @Id
    @GeneratedValue
    public int getId() {
        return Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

     /**
     * The roleName of the Role in Bookstore_Role table 
     * Not null value
     * Get and Set functions to access the attribute
     * @return a String
     */
    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}
